/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_appsync_graphqlEndpoint": "https://rzehqbchbjf6hfsiukktxhuen4.appsync-api.ap-south-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-south-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-vbobzrzwhfguzkiwail3lt7loi",
    "aws_cognito_identity_pool_id": "ap-south-1:6270b7bc-d912-4c51-8527-a8a1614638a8",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_OmJG8IjKV",
    "aws_user_pools_web_client_id": "55q0rcgjak1tuho85nu3pmud0h",
    "oauth": {
        "domain": "zenverse0b542ece-0b542ece-auth.auth.ap-south-1.amazoncognito.com",
        "scope": [
            "aws.cognito.signin.user.admin",
            "email",
            "openid",
            "phone",
            "profile"
        ],
        "redirectSignIn": "http://localhost:3000/,https://dev.d1zumicxzxxdjk.amplifyapp.com/,https://subproj-auth.d1zumicxzxxdjk.amplifyapp.com/",
        "redirectSignOut": "http://localhost:3000/,https://dev.d1zumicxzxxdjk.amplifyapp.com/,https://subproj-auth.d1zumicxzxxdjk.amplifyapp.com/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [
        "GOOGLE"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "zenverse-storage-a17c6a0950007-contmgmt",
    "aws_user_files_s3_bucket_region": "ap-south-1"
};


export default awsmobile;
